-- <!-- AGENT: ARCHITECT -->
-- Rationale:
-- Storage objects are tenant data. Public-facing artwork may be anonymously
-- readable, but only church managers may mutate it. Payment proofs can contain
-- financial and personal information, so they must be private and accessed
-- through short-lived signed URLs generated by server-side code.

UPDATE storage.buckets
SET
  public = TRUE,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp']
WHERE id IN ('event-covers', 'payment-qr');

UPDATE storage.buckets
SET
  public = TRUE,
  file_size_limit = 2097152,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp']
WHERE id = 'people-photos';

UPDATE storage.buckets
SET
  public = FALSE,
  file_size_limit = 5242880,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp']
WHERE id = 'payment-proofs';

DROP POLICY IF EXISTS "Public View Access for Payment Proofs" ON storage.objects;

CREATE POLICY tenant_image_insert_managers
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id IN ('event-covers', 'payment-qr', 'people-photos')
    AND EXISTS (
      SELECT 1
      FROM public.church_memberships AS membership
      WHERE membership.user_id = (SELECT auth.uid())
        AND membership.role IN ('owner', 'admin')
        AND membership.church_id::TEXT = (storage.foldername(name))[1]
    )
  );

CREATE POLICY tenant_image_update_managers
  ON storage.objects
  FOR UPDATE
  TO authenticated
  USING (
    bucket_id IN ('event-covers', 'payment-qr', 'people-photos')
    AND EXISTS (
      SELECT 1
      FROM public.church_memberships AS membership
      WHERE membership.user_id = (SELECT auth.uid())
        AND membership.role IN ('owner', 'admin')
        AND membership.church_id::TEXT = (storage.foldername(name))[1]
    )
  )
  WITH CHECK (
    bucket_id IN ('event-covers', 'payment-qr', 'people-photos')
    AND EXISTS (
      SELECT 1
      FROM public.church_memberships AS membership
      WHERE membership.user_id = (SELECT auth.uid())
        AND membership.role IN ('owner', 'admin')
        AND membership.church_id::TEXT = (storage.foldername(name))[1]
    )
  );

CREATE POLICY tenant_image_delete_managers
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id IN ('event-covers', 'payment-qr', 'people-photos')
    AND EXISTS (
      SELECT 1
      FROM public.church_memberships AS membership
      WHERE membership.user_id = (SELECT auth.uid())
        AND membership.role IN ('owner', 'admin')
        AND membership.church_id::TEXT = (storage.foldername(name))[1]
    )
  );

-- Rollback plan:
-- 1. DROP POLICY tenant_image_insert_managers,
--    tenant_image_update_managers, and tenant_image_delete_managers on
--    storage.objects.
-- 2. Set payment-proofs.public back to TRUE and recreate the former public
--    SELECT policy only if exposing payment evidence is explicitly accepted.
-- 3. Set file_size_limit and allowed_mime_types to NULL to remove bucket-level
--    restrictions.

